name: SBOM PR

on:
  pull_request:
    types: ['opened', 'synchronize']

env:
  CI: true
  API_KEY: ${{secrets.DEV_DEP_TRACK_API_KEY}}
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  FETCH_LICENSE: true

jobs:
  sbom-pr:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Upload SBOM
        run: yarn dlx @cyclonedx/cdxgen --api-key $API_KEY --server-url https://dependency-track-api.dev.paas.reapit.cloud --project-name foundations --project-version "$(git branch --show-current)"