name: Check PR

on:
  pull_request:
    types: ['opened', 'synchronize']

env:
  CI: true
  API_KEY: ${{secrets.DEV_DEP_TRACK_API_KEY}}

jobs:
  test-pr:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Upload SBOM
        run: npx @cyclonedx/cdxgen --api-key $API_KEY --server-url https://dependency-track.dev.paas.reapit.cloud --project-name $GITHUB_ACTION_REPOSITORY --project-version $GITHUB_REF_NAME